### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by viveksatasiya** [nucleartux/react-native-date#3]
When I try to run sudo react-native run-android command after adding all dependancies to project, I get following error:

```
/home/upc3/rnd/projects/react-native/Qmantic/android/app/src/main/java/com/qmantic/MainActivity.java:32: error: constructor ReactDatePackage in class ReactDatePackage cannot be applied to given types;
                .addPackage(new ReactDatePackage(this))
                            ^
  required: FragmentActivity
  found: MainActivity
  reason: actual argument MainActivity cannot be converted to FragmentActivity by method invocation conversion
1 error
:app:compileDebugJavaWithJavac FAILED
```

What I am missing??
Please hele me.
Thanks

**Comment by nucleartux** [comment]
You forgot change extend block in your application activity class from FragmentActivity, not from Activity.
Add this line at top of MainActivity.java:
import android.support.v4.app.FragmentActivity;
And replace extends to:
public class MainActivity extends FragmentActivity

**Comment by viveksatasiya** [comment]
sorry it was my mistake.
I forgot to add dependency.
Thanks a lot.
