### ISSUE TITLE
Installation Build Errors

### ISSUE THREAD

**Issue by drosko** [nucleartux/react-native-date#4]
Hi, when I do step 4 of the installation instructions, I get build errors.  My MainActivity Class looks different, maybe because it uses Activity vs. FragmentActivity? For example I have:

import android.app.Activity;.......

and

public class MainActivity extends Activity implements DefaultHardwareBackBtnHandler {

...instead of extending FragmentActivity. Sorry I am not familiar with android, just wondered if you might have a quick fix or suggestion.

**Comment by aakashns** [comment]
I added 

``` java
import android.support.v4.app.FragmentActivity;
```

and changed the `MainActivity` of my app to extend `FragmentActivity` instead of `Activity` and it worked.

**Comment by peterlazar1993** [comment]
https://github.com/nucleartux/react-native-date/issues/3
It's not a bug check the above issue.
